process.env.TZ='UTC';
const fs=require('fs'),vm=require('vm'),assert=require('assert'),path=require('path');const html=fs.readFileSync(path.join(__dirname,'..','index.html'),'utf8'),src=html.split('<script>')[1].split('</script>')[0];let now=0,wall=Date.parse('2026-10-10T01:00:00Z');const disk={},nodes={},listeners={},drawn=[],timeouts=new Map();let timerSequence=0;function parse(s){for(const m of s.matchAll(/<(?:input|select|details|div|button|p|span)[^>]*\bid="([^"]+)"[^>]*>/g)){const e=node(m[1]);const value=m[0].match(/\bvalue="([^"]*)"/);if(value)e.value=value[1];e.checked=/\bchecked/.test(m[0]);}}function node(id){if(nodes[id])return nodes[id];let content='';const x={id,value:'',classList:{values:new Set(),add(c){this.values.add(c)},remove(c){this.values.delete(c)},toggle(c,b){if(b===undefined)b=!this.values.has(c);b?this.values.add(c):this.values.delete(c)},contains(c){return this.values.has(c)}},textContent:'',style:{setProperty(){}},append(){},remove(){},click(){},querySelector(){return null},querySelectorAll(){return []},checked:false,scrollIntoView(){},setAttribute(){},showModal(){this.open=true},close(){this.open=false},focus(){},blur(){},addEventListener(k,f){this.events??={};this.events[k]=f},contains(){return false}};Object.defineProperty(x,'innerHTML',{get:()=>content,set:s=>{content=s;parse(s)}});nodes[id]=x;return x;}parse(html);class FakeDate extends Date{constructor(...args){super(...(args.length?args:[wall]))}static now(){return wall}}
const context={console,Date:FakeDate,performance:{now:()=>now},setTimeout:(f,ms)=>{const id=++timerSequence;timeouts.set(id,{f,ms});return id},clearTimeout:id=>timeouts.delete(id),setInterval(){},confirm:()=>true,localStorage:{getItem:k=>disk[k]??null,setItem:(k,v)=>disk[k]=v,removeItem:k=>delete disk[k]},URL:{createObjectURL:()=>'',revokeObjectURL(){}},document:{body:node('body'),getElementById:node,querySelectorAll:()=>[],querySelector:()=>node('coinarea'),hidden:false,addEventListener:(k,f)=>listeners[k]=f,createElement:type=>type==='canvas'?{getContext:()=>({createLinearGradient:()=>({addColorStop(){}}),fillRect(){},fillText:t=>drawn.push(t)}),toBlob:f=>f({})}:node(type)},window:{matchMedia:()=>({matches:false}),scrollTo(){},addEventListener:(k,f)=>listeners[k]=f}};vm.createContext(context);vm.runInContext(src,context);const run=s=>vm.runInContext(s,context);
run("state.A={...blank(),monthlyNet:'10000',dailySpanHours:'9',dailyWorkHours:'8',dailyBreakMinutes:'60',commuteRoundTripMinutes:'60',scheduleMode:'actual',actualWorkDays:'240'};calculate()");assert(nodes.results.innerHTML.includes('62.50'));assert(nodes.results.innerHTML.includes('50.00'));assert(nodes.trialResult.innerHTML.includes('50.00'));run('detailSource="mine";renderDetails()');assert.equal(run('detailData().I'),120000);assert.equal(run('detailData().x[0].T'),2400);assert.equal(run('detailData().x[0].W'),1920);for(let i=0;i<8;i++){run(`detailIndex=${i};renderDetails()`);assert(nodes.detailPanel.innerHTML.includes('共同假设'));assert(!nodes.detailPanel.innerHTML.includes('NaN'));assert(!nodes.detailPanel.innerHTML.includes('Infinity'));}
run('makeShareCard()');assert(drawn.includes('收入已隐藏'));drawn.length=0;nodes.shareIncome.checked=true;run('makeShareCard()');assert(drawn.some(t=>t.includes('120,000.00')));
run("show('blood');start()");now=60000;run('loop(performance.now())');assert.equal(nodes.earnings.textContent,'1.04');run('pause()');now=120000;assert.equal(run('elapsed()'),60000);run('start()');now=180000;run('end()');assert.equal(run('elapsed()'),120000);run('restart();basis="occupied";start()');now=240000;run('loop(performance.now())');assert.equal(nodes.earnings.textContent,'0.83');context.document.hidden=true;listeners.visibilitychange();assert.equal(run('state.session.status'),'running');run('pause()');context.document.hidden=false;
run("state.session=null;state.timePrefs=null;basis='work'");nodes.workStart.value='2026-10-10T00:00';nodes.workEnd.value='2026-10-10T02:00';nodes.backfillPause.value='30';nodes.backfill.onclick();assert.equal(run('state.session.elapsed'),1800000);assert.equal(run('state.session.backfilled'),1800000);assert.equal(run('state.session.status'),'running');assert.equal(nodes.earnings.textContent,'31.25');wall=Date.parse('2026-10-10T02:00:00Z');run('paintCountdown()');assert.equal(run('state.session.status'),'running');assert(nodes.countdown.textContent.includes('预计下班'));run('end()');
run("state.A={...state.A,scheduleMode:'shifts',shifts:[{days:'120',span:'9',rest:'60',commute:'60'},{days:'120',span:'9',rest:'60',commute:'0'}]}");nodes.copyA.onclick();run("state.B.shifts[0].days='10'");assert.equal(run('state.A.shifts[0].days'),'120');run('calculate();detailSource="mine";renderDetails()');assert.equal(run('detailData().x[0].T'),2280);console.log('V1.3运行检查通过：初始化、8类详情一致性、试算、分享隐私、秒薪、暂停、补录、到点结束和A/B档案独立。');

run("state.A={...blank(),monthlyNet:'10000',dailySpanHours:String(8+35/60),dailyWorkHours:'8',dailyBreakMinutes:'35',commuteRoundTripMinutes:'60',scheduleMode:'actual',actualWorkDays:'240'}");assert.equal(run('getA().work'),62.5);console.log('旧版非整小时午休档案迁移检查通过。');
// New accounting: wall deadline splits only active intervals, prices apply prospectively.
run("pause();state.session=null;state.timePrefs=null;state.A={...blank(),monthlyNet:'10000',dailySpanHours:'9',dailyWorkHours:'8',dailyBreakMinutes:'60',commuteRoundTripMinutes:'60',scheduleMode:'actual',actualWorkDays:'240'};basis='work'");
wall=Date.parse('2026-10-10T01:59:00Z');now=1000000;nodes.workStart.value='2026-10-10T00:00';nodes.workEnd.value='2026-10-10T02:00';nodes.overtimeMode.value='unpaid';nodes.applyTimes.onclick();run('start()');now+=120000;wall+=120000;run('loop(performance.now())');assert.equal(run('sessionTotals().regularMs'),60000);assert.equal(run('sessionTotals().unpaidMs'),60000);assert.equal(run('sessionTotals().overtimeAmount'),0);assert.equal(nodes.earnings.textContent,'1.04');assert.equal(nodes.unpaidClock.textContent,'00:01:00');
// Enable 120/h after one unpaid minute; no retroactive pay.
nodes.overtimeMode.value='paid';nodes.overtimePrice.value='120';nodes.overtimeMode.onchange();now+=60000;wall+=60000;run('loop(performance.now())');assert.equal(run('sessionTotals().overtimeAmount'),2);assert.equal(run('sessionTotals().unpaidMs'),60000);assert.equal(nodes.earnings.textContent,'3.04');
// New 60/h does not rewrite previous 120/h minute.
nodes.overtimePrice.value='60';nodes.overtimePrice.onchange();now+=60000;wall+=60000;run('pause()');assert.equal(run('sessionTotals().overtimeAmount'),3);const amt=run('sessionTotals().amount');now+=3600000;wall+=3600000;assert.equal(run('sessionTotals().amount'),amt);assert.equal(run('sessionTotals().elapsed'),240000);run('start()');now+=60000;wall+=60000;run('pause()');assert.equal(run('sessionTotals().overtimeAmount'),4);
run('save()');const stored=JSON.parse(disk['work-recharge-local-v1.1']);assert.equal(stored.session.overtimeAmount,4);assert.equal(stored.session.unpaidMs,60000);
// Pause before deadline, resume after it: paused interval earns nothing.
run('state.session=null');wall=Date.parse('2026-10-10T01:59:00Z');nodes.overtimeMode.value='unpaid';nodes.applyTimes.onclick();run('start()');now+=30000;wall+=30000;run('pause()');now+=120000;wall+=120000;run('start()');now+=30000;wall+=30000;run('pause()');assert.equal(run('sessionTotals().regularMs'),30000);assert.equal(run('sessionTotals().unpaidMs'),30000);assert.equal(run('elapsed()'),60000);
// Auto-end clamps delayed ticks at deadline.
run('state.session=null');wall=Date.parse('2026-10-10T01:59:00Z');nodes.applyTimes.onclick();run('start()');now+=120000;wall+=120000;run('loop(performance.now())');assert.equal(run('state.session.status'),'running');assert.equal(run('elapsed()'),120000);assert.equal(run('sessionTotals().unpaidMs'),60000);run('pause()');
// Backfill includes overtime, with independently deducted breaks.
wall=Date.parse('2026-10-10T03:00:00Z');nodes.workStart.value='2026-10-10T00:00';nodes.workEnd.value='2026-10-10T02:00';nodes.backfillPause.value='30';nodes.backfillOtPause.value='15';nodes.overtimeMode.value='unpaid';nodes.backfill.onclick();assert.equal(run('sessionTotals().regularMs'),5400000);assert.equal(run('sessionTotals().unpaidMs'),2700000);assert.equal(run('sessionTotals().amount'),93.75);nodes.overtimeMode.value='paid';nodes.overtimePrice.value='60';nodes.backfill.onclick();assert.equal(run('sessionTotals().unpaidMs'),0);assert.equal(run('sessionTotals().overtimeAmount'),45);assert.equal(run('sessionTotals().amount'),138.75);
// Invalid price rejected; previous price and totals preserved.
const prev=run('state.session.overtimeRate');nodes.overtimePrice.value='-10';nodes.overtimePrice.onchange();assert.equal(run('state.session.overtimeRate'),prev);assert(nodes.toast.textContent.includes('加班单价'));nodes.overtimePrice.value='60';
// Page companion keeps navigation running; closing outside session pauses.
nodes.openCorner.onclick();assert(run('cornerOpen'));run("show('calc')");assert.equal(run('state.session.status'),'running');assert.equal(nodes.cornerMoney.textContent,'138.75');nodes.cornerPause.onclick();assert.equal(run('state.session.status'),'paused');run('finishReview(true)');nodes.cornerPause.onclick();assert.equal(run('state.session.status'),'running');nodes.cornerClose.onclick();assert.equal(run('state.session.status'),'running');run('pause()');
(async()=>{await nodes.openPip.onclick();assert(run('cornerOpen'));assert(nodes.toast.textContent.includes('未提供'));const events={},pn={};const pipNode=id=>pn[id]||(pn[id]={textContent:'',disabled:false,classList:{toggle(){}}});context.window.documentPictureInPicture={requestWindow:async()=>({closed:false,document:{documentElement:{},head:{append(){}},body:{},createElement:()=>({}),getElementById:pipNode},addEventListener:(k,f)=>events[k]=f,focus(){}})};await nodes.openPip.onclick();assert(run('floatingActive()'));assert.equal(pn.pipMoney.textContent,'¥ 138.75');run('start()');context.document.hidden=true;listeners.visibilitychange();assert.equal(run('state.session.status'),'running');now+=60000;wall+=60000;run('loop(performance.now())');assert.equal(pn.pipMoney.textContent,'¥ 139.75');events.pagehide();assert.equal(run('state.session.status'),'running');run('pause()');context.document.hidden=false;testNewUI();testManualClose();testBuddy();testClockButtons();console.log('V1.8检查通过：跨下班分段、无偿默认、改价不追溯、暂停边界、到点截断、两段补录、无效价格拦截、小窗同步与悬浮降级。')})().catch(e=>{console.error(e);process.exitCode=1});

function testNewUI(){
context.window.documentPictureInPicture=null;run("state.session=null;state.timePrefs=null;show('blood');openCorner()");assert(!nodes.corner.classList.contains('collapsed'));const idle=run('cornerTimer');assert.equal(timeouts.get(idle).ms,8000);timeouts.get(idle).f();assert(nodes.corner.classList.contains('collapsed'));nodes.corner.events.pointerenter({pointerType:'mouse'});assert(!nodes.corner.classList.contains('collapsed'));nodes.cornerFold.onclick();assert(nodes.corner.classList.contains('collapsed'));nodes.corner.events.pointerleave();assert(nodes.corner.classList.contains('collapsed'));nodes.compactClose.onclick();assert(nodes.corner.classList.contains('hidden'));assert(!nodes.restoreCorner.classList.contains('hidden'));nodes.restoreCorner.onclick();assert(!nodes.corner.classList.contains('hidden'));
// Mouse focus must not hold a stationary handle open forever.
context.document.activeElement=nodes.cornerHandle;nodes.corner.contains=e=>e===nodes.cornerHandle;nodes.cornerHandle.blur=()=>context.document.activeElement=null;run('cornerHover=false;keyboardInteraction=false;scheduleCornerFold()');timeouts.get(run('cornerTimer')).f();assert(nodes.corner.classList.contains('collapsed'));assert.equal(context.document.activeElement,null);
// Keyboard focus remains usable, and Escape hides it.
run('expandCorner();keyboardInteraction=true');context.document.activeElement=nodes.cornerHandle;timeouts.get(run('cornerTimer')).f();assert(!nodes.corner.classList.contains('collapsed'));listeners.keydown({key:'Escape'});assert(nodes.corner.classList.contains('hidden'));
// Split date inputs commit without recurring date parsing during ticks.
nodes.workStartDate.value='2026-10-10';nodes.workStartTime.value='20:00';nodes.workStartDate.events.input();assert.equal(nodes.workStart.value,'2026-10-10T20:00');nodes.endNextDay.onclick();nodes.workEndTime.value='08:00';nodes.workEndTime.events.change();assert.equal(nodes.workEnd.value,'2026-10-11T08:00');assert.equal(run('getTimes().end-getTimes().start'),43200000);
// Input focus freezes display, never the underlying accounting.
wall=Date.parse('2026-10-10T20:00:00Z');nodes.overtimeMode.value='unpaid';nodes.applyTimes.onclick();run('start()');const before=nodes.earnings.textContent;nodes.workStartDate.events.focus();now+=60000;wall+=60000;run('loop(performance.now())');assert.equal(nodes.earnings.textContent,before);assert.equal(run('sessionTotals().regularMs'),60000);nodes.workStartDate.events.blur();assert.equal(nodes.earnings.textContent,'1.04');
// An ended record retains its timing/rate snapshot when next-shift settings are changed.
run('end()');const locked=run('state.session.deadline');nodes.workEnd.value='2026-10-11T09:00';nodes.applyTimes.onclick();assert.equal(run('state.session.deadline'),locked);run('renderFreeTime()');assert(!nodes.freeResult.textContent.includes('NaN'));
// Clear resets all date and pause inputs, not just the saved profile.
nodes.backfillPause.value='30';nodes.backfillOtPause.value='15';nodes.clear.onclick();assert.equal(nodes.backfillPause.value,'0');assert.equal(nodes.backfillOtPause.value,'0');assert.equal(run('state.session'),null);assert.equal(nodes.workStartDate.value,nodes.workStart.value.split('T')[0]);console.log('新增交互检查通过：8秒收起、移入展开、手动收起不反弹、两态隐藏与恢复、鼠标/键盘焦点、跨夜日期、编辑期间持续计时、结束快照保护与清空重置。');
}

function testManualClose(){
// Deadline, visibility and navigation must never stop an open shift.
run("pause();state.session=null;state.timePrefs=null;state.A={...blank(),monthlyNet:'10000',dailySpanHours:'9',dailyWorkHours:'8',dailyBreakMinutes:'60',commuteRoundTripMinutes:'60',scheduleMode:'actual',actualWorkDays:'240'};show('blood')");wall=Date.parse('2026-10-10T17:59:00Z');nodes.workStart.value='2026-10-10T09:00';nodes.workEnd.value='2026-10-10T18:00';nodes.overtimeMode.value='unpaid';nodes.applyTimes.onclick();run('start()');now+=660000;wall+=660000;run('loop(performance.now())');assert.equal(run('state.session.status'),'running');assert.equal(run('sessionTotals().unpaidMs'),600000);assert.equal(run('sessionTotals().regularMs'),60000);context.document.hidden=true;listeners.visibilitychange();now+=300000;wall+=300000;run('loop(performance.now())');assert.equal(run('state.session.status'),'running');assert.equal(run('sessionTotals().unpaidMs'),900000);context.document.hidden=false;run("show('calc')");assert.equal(run('state.session.status'),'running');
// Freeze at click, reject invalid corrections, apply only unpaid duration.
nodes.start.onclick();assert(run('stopReview!==null'));assert.equal(run('state.session.status'),'paused');assert.equal(nodes.reviewMinutes.value,'15.000');const amount=run('sessionTotals().amount');now+=60000;wall+=60000;assert.equal(run('sessionTotals().unpaidMs'),900000);nodes.reviewMinutes.value='-1';nodes.reviewConfirm.onclick();assert(run('stopReview!==null'));assert(nodes.reviewError.textContent.includes('有效'));nodes.reviewMinutes.value='8';nodes.reviewConfirm.onclick();assert.equal(run('stopReview'),null);assert.equal(run('sessionTotals().unpaidMs'),480000);assert.equal(run('sessionTotals().overtimeMs'),480000);assert.equal(run('sessionTotals().regularMs'),60000);assert.equal(run('sessionTotals().amount'),amount);assert.equal(run('state.session.status'),'paused');assert.equal(run('state.session.unpaidAdjustments.length'),1);
// Cancel resumes; time spent confirming is excluded.
run('start()');now+=60000;wall+=60000;nodes.end.onclick();assert(nodes.reviewConfirm.textContent.includes('下班'));const frozen=run('elapsed()');now+=120000;wall+=120000;nodes.reviewCancel.onclick();assert.equal(run('state.session.status'),'running');assert.equal(run('elapsed()'),frozen);now+=60000;wall+=60000;nodes.end.onclick();nodes.reviewMinutes.value='5';nodes.reviewConfirm.onclick();assert.equal(run('state.session.status'),'ended');assert.equal(run('sessionTotals().unpaidMs'),300000);const final=run('elapsed()');now+=300000;wall+=300000;assert.equal(run('elapsed()'),final);
// Ended records can be corrected again and remain ended; paid OT isn't rewritten.
nodes.reviewUnpaid.onclick();nodes.reviewMinutes.value='6';nodes.reviewConfirm.onclick();assert.equal(run('state.session.status'),'ended');assert.equal(run('sessionTotals().unpaidMs'),360000);assert.equal(run('sessionTotals().overtimeAmount'),0);run('save()');assert.equal(JSON.parse(disk['work-recharge-local-v1.1']).session.unpaidMs,360000);
run("state.session.status='paused';state.session.overtimeMs=state.session.unpaidMs+60000;state.session.overtimeAmount=2");const earned=run('sessionTotals().amount');nodes.reviewUnpaid.onclick();nodes.reviewMinutes.value='2';nodes.reviewConfirm.onclick();assert.equal(run('sessionTotals().overtimeAmount'),2);assert.equal(run('sessionTotals().overtimeMs'),180000);assert.equal(run('sessionTotals().amount'),earned);const pdNodes={},pd={getElementById:id=>pdNodes[id]||(pdNodes[id]={value:'',textContent:'',focus(){},showModal(){},close(){}})};context.reviewDoc=pd;run("requestStop('ended',reviewDoc)");assert(pdNodes.reviewConfirm.textContent.includes('下班'));pdNodes.reviewMinutes.value='1';pdNodes.reviewConfirm.onclick();assert.equal(run('state.session.status'),'ended');assert.equal(run('sessionTotals().unpaidMs'),60000);assert.equal(run('sessionTotals().overtimeAmount'),2);console.log('手动收工检查通过：到点/后台/换页不断计时，暂停核对、非法值拦截、人工修正、不改收入、取消继续、结束锁定与再次修正。');
}

function testBuddy(){
run("state.session.status='running';state.session.deadline=Date.now()+3600000;runStart=performance.now();runWallStart=Date.now();paintBuddy();openCorner()");assert(nodes.corner.classList.contains('brick-work'));assert(!nodes.restoreCorner.classList.contains('brick-static'));nodes.cornerClose.onclick();assert(nodes.corner.classList.contains('hidden'));assert(!nodes.restoreCorner.classList.contains('hidden'));assert.equal(nodes.hpStatus.textContent,'回血中');assert(html.includes('@keyframes hp-shine'));assert(html.includes('class="brick-character"'));
run('state.session.deadline=Date.now()-1;state.session.overtimeRate=0;paintBuddy()');assert(nodes.restoreCorner.classList.contains('brick-overtime'));assert.equal(nodes.hpStatus.textContent,'无偿计时中');run('pause();paintBuddy()');assert(nodes.restoreCorner.classList.contains('brick-rest'));nodes.petAnimation.checked=false;nodes.petAnimation.onchange();assert(nodes.restoreCorner.classList.contains('brick-static'));nodes.petAnimation.checked=true;nodes.petAnimation.onchange();assert(!nodes.restoreCorner.classList.contains('brick-static'));run("state.session.status='ended';paintBuddy()");assert(nodes.restoreCorner.classList.contains('brick-done'));assert.equal(nodes.hpStatus.textContent,'已收工');nodes.restoreCorner.onclick();assert(!nodes.corner.classList.contains('hidden'));assert(nodes.restoreCorner.classList.contains('hidden'));const earning=run('sessionTotals().amount');run('paintBuddy()');assert.equal(run('sessionTotals().amount'),earning);console.log('板砖动效检查通过：工作/无偿/休息/收工状态、隐藏血条与恢复、动效开关，以及计时金额不受动画影响。');
}

function testClockButtons(){
run("pause();state.session=null;state.timePrefs=null;state.recentSessions=[];state.A={...blank(),monthlyNet:'10000',dailySpanHours:'9',dailyWorkHours:'8',dailyBreakMinutes:'60',commuteRoundTripMinutes:'60',scheduleMode:'actual',actualWorkDays:'240'}");wall=Date.parse('2026-10-12T10:00:00Z');nodes.workStart.value='2026-10-10T09:00';nodes.workEnd.value='2026-10-10T18:00';nodes.overtimeMode.value='unpaid';nodes.clockIn.onclick();assert.equal(run('state.session.status'),'running');assert.equal(nodes.workEnd.value,'2026-10-12T18:00');assert(nodes.clockIn.disabled);now+=60000;wall+=60000;const elapsedBefore=run('elapsed()');nodes.clockIn.onclick();assert.equal(run('elapsed()'),elapsedBefore);assert.equal(run('state.session.status'),'running');run('pause()');nodes.cornerClockIn.onclick();assert.equal(run('state.session.status'),'running');assert.equal(run('elapsed()'),elapsedBefore);nodes.clockOut.onclick();assert(run('stopReview!==null'));nodes.reviewCancel.onclick();assert.equal(run('state.session.status'),'running');nodes.clockOut.onclick();nodes.reviewConfirm.onclick();assert.equal(run('state.session.status'),'ended');assert(nodes.clockOut.disabled);assert(!nodes.clockIn.disabled);const old=run('state.session');nodes.clockIn.onclick();assert.equal(run('state.session.status'),'running');assert.equal(run('elapsed()'),0);assert.equal(run('state.recentSessions.length'),1);assert.equal(run('state.recentSessions[0].elapsed'),old.elapsed);assert(nodes.lastShiftSummary.textContent.includes('上次收工'));
// Fresh night shift shifts dates together; failed config preserves previous record.
run('end()');wall=Date.parse('2026-10-13T20:00:00Z');nodes.workStart.value='2026-10-12T20:00';nodes.workEnd.value='2026-10-13T08:00';nodes.clockIn.onclick();assert.equal(nodes.workStart.value,'2026-10-13T20:00');assert.equal(nodes.workEnd.value,'2026-10-14T08:00');assert.equal(run('state.session.deadline'),Date.parse('2026-10-14T08:00:00Z'));run('end()');const record=run('state.session');nodes.workEnd.value='';nodes.clockIn.onclick();assert.equal(run('state.session'),record);assert.equal(run('state.session.status'),'ended');console.log('一键上下班检查通过：开始、防重复、暂停续计、下班核对与取消、新班归档、旧日期及夜班迁移、无效配置不丢记录。');
}
